### ISSUE TITLE
翻译（ “根据指定的比较操作返回最终元素的索引”）不准确

### ISSUE THREAD

**Issue by ssbunny** [xswei/d3js_doc#3]
d3.scan 部分，“根据指定的比较操作返回最终元素的索引”不准确，不是“最终”，而是“最小”。因此后面才会说“这个方法与min类似”。

**Comment by xswei** [comment]
返回最小还是最大，是由传入的比较器函数决定的，最后返回的结果未必是最小的，因此使用“最终“

**Comment by ssbunny** [comment]
@xswei 原文 least
